import { Injectable } from '@nestjs/common';
import { Counter, Histogram } from 'prom-client';
import { MetricsService } from '../../metrics/metrics.service';

/**
 * Registered on the shared Prometheus registry so `/metrics` stays a
 * single scrape target. Every label is drawn from a closed set — decision
 * categories, the four priority levels, the plan status union and fixed
 * result words — so no tenant, user, plan, approval, workflow id or prompt
 * text can become a label.
 */
@Injectable()
export class AutonomousWorkflowPlanMetrics {
  private readonly generated: Counter<string>;
  private readonly generationDuration: Histogram<string>;
  private readonly approvalSubmissions: Counter<'result'>;
  private readonly byCategory: Counter<'category'>;
  private readonly byPriority: Counter<'priority'>;
  private readonly byStatus: Counter<'status'>;
  private readonly stepCount: Histogram<string>;
  private readonly handoffAttempts: Counter<string>;
  private readonly handoffOutcomes: Counter<'result'>;
  private readonly rejected: Counter<string>;
  private readonly expired: Counter<string>;

  constructor(metrics: MetricsService) {
    const registers = [metrics.registry];
    this.generated = new Counter({
      name: 'voltx_workflow_plans_generated_total',
      help: 'Workflow plans generated',
      registers,
    });
    this.generationDuration = new Histogram({
      name: 'voltx_workflow_plan_generation_duration_seconds',
      help: 'Workflow plan generation duration in seconds',
      buckets: [0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5],
      registers,
    });
    this.approvalSubmissions = new Counter({
      name: 'voltx_workflow_plan_approval_submissions_total',
      help: 'Workflow plan approval submissions by result',
      labelNames: ['result'] as const,
      registers,
    });
    this.byCategory = new Counter({
      name: 'voltx_workflow_plans_by_category_total',
      help: 'Workflow plans generated by decision category',
      labelNames: ['category'] as const,
      registers,
    });
    this.byPriority = new Counter({
      name: 'voltx_workflow_plans_by_priority_total',
      help: 'Workflow plans generated by priority',
      labelNames: ['priority'] as const,
      registers,
    });
    this.byStatus = new Counter({
      name: 'voltx_workflow_plans_by_status_total',
      help: 'Workflow plans observed by lifecycle status',
      labelNames: ['status'] as const,
      registers,
    });
    this.stepCount = new Histogram({
      name: 'voltx_workflow_plan_step_count',
      help: 'Step count distribution across generated plans',
      buckets: [1, 2, 3, 4, 5, 6],
      registers,
    });
    this.handoffAttempts = new Counter({
      name: 'voltx_workflow_plan_handoff_attempts_total',
      help: 'Execution handoff attempts',
      registers,
    });
    this.handoffOutcomes = new Counter({
      name: 'voltx_workflow_plan_handoff_results_total',
      help: 'Execution handoff outcomes by result',
      labelNames: ['result'] as const,
      registers,
    });
    this.rejected = new Counter({
      name: 'voltx_workflow_plans_rejected_total',
      help: 'Workflow plans observed transitioning to rejected',
      registers,
    });
    this.expired = new Counter({
      name: 'voltx_workflow_plans_expired_total',
      help: 'Workflow plans observed transitioning to expired',
      registers,
    });
  }

  recordGenerated(count: number): void {
    if (count > 0) this.generated.inc(count);
  }

  recordGenerationDuration(durationMs: number): void {
    this.generationDuration.observe(durationMs / 1000);
  }

  /** `category` is a fixed DecisionCategory union member. */
  recordCategory(category: string): void {
    this.byCategory.inc({ category });
  }

  recordPriority(priority: string): void {
    this.byPriority.inc({ priority });
  }

  recordStatus(status: string): void {
    this.byStatus.inc({ status });
  }

  recordStepCount(steps: number): void {
    this.stepCount.observe(steps);
  }

  recordApprovalSubmission(result: 'success' | 'failure' | 'idempotent'): void {
    this.approvalSubmissions.inc({ result });
  }

  recordHandoffAttempt(): void {
    this.handoffAttempts.inc();
  }

  recordHandoffOutcome(result: 'success' | 'failure'): void {
    this.handoffOutcomes.inc({ result });
  }

  recordRejected(): void {
    this.rejected.inc();
  }

  recordExpired(): void {
    this.expired.inc();
  }
}
