import 'dart:convert';
import 'dart:io';

const defaultSource = 'http://localhost:3000/api-json';
const schemaNames = <String>[
  'CreatePersonalAccessTokenDto',
  'CreateServiceAccountDto',
  'CreateServiceAccountTokenDto',
  'CreateOAuthApplicationDto',
  'UpdateOAuthApplicationDto',
  'CreateWebhookEndpointDto',
  'UpdateWebhookEndpointDto',
];

String dartTypeFor(Map<String, dynamic> schema) {
  final type = schema['type'] as String?;
  switch (type) {
    case 'array':
      final items =
          (schema['items'] as Map?)?.cast<String, dynamic>() ??
          <String, dynamic>{};
      return 'List<${dartTypeFor(items)}>';
    case 'integer':
      return 'int';
    case 'boolean':
      return 'bool';
    default:
      return 'String';
  }
}

String renderClass(String name, Map<String, dynamic> schema) {
  final properties =
      (schema['properties'] as Map?)?.cast<String, dynamic>() ??
      <String, dynamic>{};
  final required = ((schema['required'] as List?) ?? const <dynamic>[])
      .map((item) => item.toString())
      .toSet();

  final requiredEntries = properties.entries
      .where((entry) => required.contains(entry.key))
      .toList();
  final optionalEntries = properties.entries
      .where((entry) => !required.contains(entry.key))
      .toList();
  final ordered = <MapEntry<String, dynamic>>[
    ...requiredEntries,
    ...optionalEntries,
  ];

  final fields = ordered
      .map((entry) {
        final prop =
            (entry.value as Map?)?.cast<String, dynamic>() ??
            <String, dynamic>{};
        final type = dartTypeFor(prop);
        final nullable = required.contains(entry.key) ? '' : '?';
        return '  final $type$nullable ${entry.key};';
      })
      .join('\n');

  final constructorArgs = ordered
      .map((entry) {
        final isRequired = required.contains(entry.key);
        final prefix = isRequired ? 'required ' : '';
        return '    ${prefix}this.${entry.key},';
      })
      .join('\n');

  final fromJsonArgs = ordered
      .map((entry) {
        final prop =
            (entry.value as Map?)?.cast<String, dynamic>() ??
            <String, dynamic>{};
        final type = dartTypeFor(prop);
        final key = entry.key;
        if (type.startsWith('List<')) {
          return "      $key: (json['$key'] as List?)?.map((item) => item.toString()).toList(),";
        }
        if (type == 'int') {
          return "      $key: json['$key'] as int${required.contains(key) ? '' : '?'},";
        }
        if (type == 'bool') {
          return "      $key: json['$key'] as bool${required.contains(key) ? '' : '?'},";
        }
        return "      $key: json['$key'] as String${required.contains(key) ? '' : '?'},";
      })
      .join('\n');

  final toJsonArgs = ordered
      .map((entry) => "      '${entry.key}': ${entry.key},")
      .join('\n');

  return '''class $name {
$fields

  const $name({
$constructorArgs
  });

  factory $name.fromJson(Map<String, dynamic> json) {
    return $name(
$fromJsonArgs
    );
  }

  Map<String, dynamic> toJson() {
    return {
$toJsonArgs
    };
  }
}''';
}

Future<void> main() async {
  final source = Platform.environment['VOLTX_OPENAPI_URL'] ?? defaultSource;
  final output = File('lib/src/generated/schema.dart');

  final client = HttpClient();
  final request = await client.getUrl(Uri.parse(source));
  final response = await request.close();
  if (response.statusCode != HttpStatus.ok) {
    stderr.writeln(
      'Failed to fetch OpenAPI document from $source (status ${response.statusCode})',
    );
    exitCode = 1;
    return;
  }

  final body = await response.transform(utf8.decoder).join();
  final document = jsonDecode(body) as Map<String, dynamic>;
  final components =
      (document['components'] as Map?)?.cast<String, dynamic>() ??
      <String, dynamic>{};
  final schemas =
      (components['schemas'] as Map?)?.cast<String, dynamic>() ??
      <String, dynamic>{};

  final blocks = <String>[];
  for (final name in schemaNames) {
    final schema = (schemas[name] as Map?)?.cast<String, dynamic>();
    if (schema == null) {
      stderr.writeln("Schema '$name' not found in OpenAPI document at $source");
      exitCode = 1;
      return;
    }
    blocks.add(renderClass(name, schema));
  }

  final generated = StringBuffer()
    ..writeln(
      '// Auto-generated by tool/generate_models.dart — do not edit by hand.',
    )
    ..writeln('// Regenerate with: dart run tool/generate_models.dart')
    ..writeln()
    ..writeln(blocks.join('\n\n'));

  await output.create(recursive: true);
  await output.writeAsString(generated.toString());
  stdout.writeln('Wrote ${blocks.length} schemas to ${output.path}');
}
