"use client";

import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, RefreshCw, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { insightsApi } from "@/lib/api/insights";

export default function ExecutiveInsightsPage() {
  const [category, setCategory] = useState("all"); const [search, setSearch] = useState("");
  const query = useQuery({ queryKey: ["executive-insights"], queryFn: insightsApi.get });
  const insights = useMemo(() => (query.data?.insights ?? []).filter((item) => (category === "all" || item.category === category) && `${item.title} ${item.summary}`.toLowerCase().includes(search.toLowerCase())), [query.data, category, search]);
  if (query.isLoading) return <div className="p-6 text-sm text-muted-foreground">Loading executive insights…</div>;
  if (query.error) return <div className="p-6"><p className="text-destructive">Insights could not be loaded.</p><Button className="mt-4" onClick={() => query.refetch()}>Retry</Button></div>;
  return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Executive insights</h1><p className="text-sm text-muted-foreground">Evidence-backed priorities. Recommendations never execute automatically.</p></div><Button variant="outline" onClick={() => query.refetch()}><RefreshCw className="h-4 w-4" />Refresh</Button></header><div className="flex flex-wrap gap-2"><input aria-label="Search insights" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search insights" className="h-9 border bg-background px-3 text-sm" /><select aria-label="Filter category" value={category} onChange={(event) => setCategory(event.target.value)} className="h-9 border bg-background px-3 text-sm"><option value="all">All categories</option>{[...new Set(query.data?.insights.map((item) => item.category) ?? [])].map((value) => <option key={value}>{value}</option>)}</select></div>{query.data?.trends.map((trend) => <p key={trend.source} className="text-sm text-muted-foreground">Historical {trend.source} trends unavailable — verified historical source is not exposed.</p>)}<section className="grid gap-4 md:grid-cols-2">{insights.map((item) => <article key={item.id} tabIndex={0} className="space-y-3 border bg-card p-4"><div className="flex justify-between gap-3"><h2 className="font-medium">{item.title}</h2><span className="text-xs uppercase text-muted-foreground">{item.confidence} confidence</span></div><p className="text-sm text-muted-foreground">{item.summary}</p><p className="text-sm">Evidence: {item.evidence.map((evidence) => evidence.label).join(", ") || "No permitted records"}</p><p className="text-sm">Supporting records: {item.supportingMetrics.recordsAvailable ?? 0}</p><p className="flex items-center gap-2 text-sm"><ShieldCheck className="h-4 w-4" />{item.recommendedAction.label} <span className="rounded bg-amber-500/15 px-2 py-0.5 text-xs">Approval required</span></p></article>)}</section>{insights.length === 0 && <div className="border p-8 text-center text-sm text-muted-foreground"><AlertTriangle className="mx-auto mb-2 h-5 w-5" />No insights match the selected filters.</div>}{query.data?.excludedSources.length ? <aside className="text-sm text-muted-foreground">Unavailable sources: {query.data.excludedSources.map((source) => `${source.source} (${source.reason})`).join(", ")}</aside> : null}</div>;
}
