#!/usr/bin/env python3
"""Regenerates voltx_sdk/generated/schema.py from a running backend's live
OpenAPI 3.1 document. Run this — and review the resulting diff — every time
the public API changes; the output is checked into the repo, never
generated silently as part of a normal build.

Uses only the standard library (no Java, no extra pip dependency for the
generator itself) since only a handful of request-body schemas need
covering: it pulls the named schemas below out of the live document's
`components.schemas` and emits a matching typed dataclass for each. Response
payload types are hand-maintained in voltx_sdk/types.py instead — NestJS
Swagger cannot resolve the backend's generic `ApiSuccessResponseDto[T]`'s
`data` field to a concrete schema, so those shapes never appear in the
document at all (same rationale as the TypeScript SDK's src/types.ts).
"""
from __future__ import annotations

import json
import os
import urllib.request
from pathlib import Path

SOURCE = os.environ.get("VOLTX_OPENAPI_URL", "http://localhost:3000/api-json")
OUT_PATH = Path(__file__).parent.parent / "voltx_sdk" / "generated" / "schema.py"

# The request-body DTOs this SDK covers, in the order they should appear.
SCHEMA_NAMES = [
    "CreatePersonalAccessTokenDto",
    "CreateServiceAccountDto",
    "CreateServiceAccountTokenDto",
    "CreateOAuthApplicationDto",
    "UpdateOAuthApplicationDto",
    "CreateWebhookEndpointDto",
    "UpdateWebhookEndpointDto",
]


def python_type(schema: dict) -> str:
    json_type = schema.get("type")
    if json_type == "array":
        return f"List[{python_type(schema.get('items', {}))}]"
    if json_type == "integer":
        return "int"
    if json_type == "boolean":
        return "bool"
    return "str"


def render_dataclass(name: str, schema: dict) -> str:
    properties: dict = schema.get("properties", {})
    required: list = schema.get("required", [])

    # Required fields must come before optional (defaulted) fields in a
    # Python dataclass — order the properties accordingly.
    ordered = [(key, val) for key, val in properties.items() if key in required] + [
        (key, val) for key, val in properties.items() if key not in required
    ]

    lines = [f"@dataclass", f"class {name}:"]
    if not ordered:
        lines.append("    pass")
    for key, prop in ordered:
        py_type = python_type(prop)
        description = prop.get("description")
        if key in required:
            lines.append(f"    {key}: {py_type}")
        else:
            lines.append(f"    {key}: Optional[{py_type}] = None")
        if description:
            comment = description.replace("\n", " ")
            lines.append(f'    """{comment}"""')
    return "\n".join(lines)


def main() -> None:
    print(f"Generating models from {SOURCE} -> {OUT_PATH}")
    with urllib.request.urlopen(SOURCE) as response:  # noqa: S310 - trusted local/dev backend URL
        document = json.load(response)

    schemas = document["components"]["schemas"]
    blocks = []
    for name in SCHEMA_NAMES:
        if name not in schemas:
            raise SystemExit(f"Schema '{name}' not found in the OpenAPI document at {SOURCE}")
        blocks.append(render_dataclass(name, schemas[name]))

    header = (
        '"""Auto-generated by scripts/generate_models.py — do not edit by hand.\n'
        "Regenerate with: python scripts/generate_models.py\n\"\"\"\n"
        "from __future__ import annotations\n\n"
        "from dataclasses import dataclass\n"
        "from typing import List, Optional\n\n"
    )
    OUT_PATH.write_text(header + "\n\n\n".join(blocks) + "\n")
    print(f"Wrote {len(blocks)} models to {OUT_PATH}")


if __name__ == "__main__":
    main()
